/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InfoRouteImport } from './routes/info'
import { Route as ClassroomIdRouteImport } from './routes/classroom.$id'
import { Route as ClassroomCampusNameRouteImport } from './routes/classroom.$campus.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassroomIdRoute = ClassroomIdRouteImport.update({
  id: '/classroom/$id',
  path: '/classroom/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassroomCampusNameRoute = ClassroomCampusNameRouteImport.update({
  id: '/classroom/$campus/$name',
  path: '/classroom/$campus/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/info': typeof InfoRoute
  '/classroom/$id': typeof ClassroomIdRoute
  '/classroom/$campus/$name': typeof ClassroomCampusNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/info': typeof InfoRoute
  '/classroom/$id': typeof ClassroomIdRoute
  '/classroom/$campus/$name': typeof ClassroomCampusNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/info': typeof InfoRoute
  '/classroom/$id': typeof ClassroomIdRoute
  '/classroom/$campus/$name': typeof ClassroomCampusNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/info' | '/classroom/$id' | '/classroom/$campus/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/info' | '/classroom/$id' | '/classroom/$campus/$name'
  id: '__root__' | '/' | '/info' | '/classroom/$id' | '/classroom/$campus/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InfoRoute: typeof InfoRoute
  ClassroomIdRoute: typeof ClassroomIdRoute
  ClassroomCampusNameRoute: typeof ClassroomCampusNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classroom/$id': {
      id: '/classroom/$id'
      path: '/classroom/$id'
      fullPath: '/classroom/$id'
      preLoaderRoute: typeof ClassroomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classroom/$campus/$name': {
      id: '/classroom/$campus/$name'
      path: '/classroom/$campus/$name'
      fullPath: '/classroom/$campus/$name'
      preLoaderRoute: typeof ClassroomCampusNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InfoRoute: InfoRoute,
  ClassroomIdRoute: ClassroomIdRoute,
  ClassroomCampusNameRoute: ClassroomCampusNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
